### ISSUE TITLE
Remember Correction puts season/episode to Smart Match

### ISSUE THREAD

**Issue by jankete** [MediaBrowser/Emby.AutoOrganize#12] opened 2018-05-19 07:19 UTC
Hi,

I have some files from for example Navy CIS named "euhd-ncis-sXXeYX.mkv". After manually matching them, the result in the Smart Matches always look like this:
![screenshot_20180519-091224 2](https://user-images.githubusercontent.com/22338766/40266113-9f9f18fa-5b45-11e8-88b8-b3909130466d.png)
So the auto organising is not working for new episodes.

Thanks
Jankete

**Comment by daed-alus** [comment] 2018-05-27 17:21
this is exactly the same as #11, it was caused by using the same watchfolder for movies and series
here it's still fixed by plugin v1.2.5.0 & server 3.4.1.8 beta

**Comment by jankete** [comment] 2018-05-28 04:33
Yes, seems to be the same ... as I use the official Synology package, I'll have to wail 'till the final versions for the plugin and/or the server come out. Thanks so far.

**Comment by PoppyPop** [comment] 2018-06-02 15:49
I you have access to the 3.4.X.X version of the server, you should have access to the update.

**Comment by jankete** [comment] 2018-06-03 06:13
Using the Emby repository for Synology my server is on 3.4.1.0 and the plugin has 1.2.3.0 - no update available.

**Closed as completed** 2019-08-02 06:10 UTC
